app/Http/Controllers/Auth/RegisterController.php
app/Http/Controllers/Auth/ResetPasswordController.php
app/Http/Middleware/RedirectIfAuthenticated.php
resources/views/layouts/metronic.blade.php
routes/web.php

https://mir24tv.atlassian.net/browse/MIP-2

wrap routes with auth middleware

---

resources/views/datatables/topic.blade.php
resources/views/layouts/metronic.blade.php

https://mir24tv.atlassian.net/browse/MIP-31

make datatable big

---

public/css/core.css
public/js/core.js
resources/views/datatables/topic.blade.php

https://mir24tv.atlassian.net/browse/MIP-36

Download button

---

resources/views/datatables/topic.blade.php

https://mir24tv.atlassian.net/browse/MIP-30

rename topic creation button

---

resources/views/datatables/topic.blade.php

https://mir24tv.atlassian.net/browse/MIP-22

pause player on modal close

---

app/Http/Controllers/TopicController.php
resources/views/datatables/topic.blade.php

https://mir24tv.atlassian.net/browse/MIP-17
https://mir24tv.atlassian.net/browse/MIP-18

add filters for created_at and orgznizations

---

resources/views/layouts/app.blade.php

https://mir24tv.atlassian.net/browse/MIP-38

add favicon to app layout

---

resources/lang/ru.json
resources/views/datatables/topic.blade.php

https://mir24tv.atlassian.net/browse/MIP-46

add translate to datatables

---

resources/views/datatables/topic.blade.php
resources/views/layouts/metronic.blade.php

https://mir24tv.atlassian.net/browse/MIP-48

remove scrollbar in datatable

---

app/Http/Controllers/TopicController.php

https://mir24tv.atlassian.net/browse/MIP-50

add custom message on url format validation in topics.store

---

resources/views/datatables/topic.blade.php

https://mir24tv.atlassian.net/browse/MIP-51

make videofile required

---

resources/lang/ru.json
resources/views/datatables/topic.blade.php

https://mir24tv.atlassian.net/browse/MIP-53

localize buttons

---

app/Console/Commands/TopicsDeleteOld.php
app/Console/Kernel.php
config/constants.php

https://mir24tv.atlassian.net/browse/MIP-28

remove old topics

---

app/Http/Controllers/OrganizationController.php
app/Http/Controllers/TopicController.php
composer.json
composer.lock
resources/views/indexes/topicsMore.blade.php
resources/views/layouts/metronic.blade.php
routes/web.php

https://mir24tv.atlassian.net/browse/MIP-59
https://mir24tv.atlassian.net/browse/MIP-68

add routes for load more in index and index by organization

---

app/Console/Commands/TopicsDeleteOld.php
app/Http/Controllers/TopicController.php
app/Topic.php
composer.json
composer.lock

https://mir24tv.atlassian.net/browse/MIP-71

localize date

---

app/Http/Controllers/OrganizationController.php
app/Http/Controllers/TopicController.php
resources/views/indexes/topics.blade.php
resources/views/layouts/front.blade.php
routes/web.php

https://mir24tv.atlassian.net/browse/MIP-67

add topic index for specific organization route

---

app/Http/Controllers/TopicController.php
routes/web.php

https://mir24tv.atlassian.net/browse/MIP-58

add topic index front route

---

resources/views/datatables/topic.blade.php
resources/views/layouts/metronic.blade.php

https://mir24tv.atlassian.net/browse/MIP-73

remove footer and datatable title from datatable page

---

public/css/core.css
resources/views/datatables/topic.blade.php

https://mir24tv.atlassian.net/browse/MIP-72

fix columns width in datatable

---

resources/views/datatables/topic.blade.php

https://mir24tv.atlassian.net/browse/MIP-78

fix grammar issue

---

public/css/core.css
resources/views/datatables/topic.blade.php

https://mir24tv.atlassian.net/browse/MIP-77

add clear organization search button

---

config/mail.php

https://mir24tv.atlassian.net/browse/MIP-83

set emain from name and address

---

resources/views/layouts/app.blade.php

https://mir24tv.atlassian.net/browse/MIP-82

fix favicon on app layout

---

app/Http/Controllers/TopicController.php
resources/views/datatables/topic.blade.php

- rm duplicate code, logic change

https://mir24tv.atlassian.net/browse/MIP-88

---

resources/views/layouts/app.blade.php

https://mir24tv.atlassian.net/browse/MIP-19

remove login from loigin page

---

app/Topic.php
database/migrations/2018_06_07_160708_add_image_url_column_to_topics_table.php

https://mir24tv.atlassian.net/browse/MIP-87

add image_url to topics table

---

resources/views/datatables/topic.blade.php

https://mir24tv.atlassian.net/browse/ST-557

remove second datatable

---

database/factories/TopicFactory.php
database/factories/UserFactory.php
database/migrations/2018_05_30_173058_videos_cdn_latest_update_nullable.php
database/seeds/DatabaseSeeder.php
database/seeds/TopicsTableSeeder.php
database/seeds/UsersTableSeeder.php

https://mir24tv.atlassian.net/browse/MIP-108

fix users and topics seeds

---

app/Http/Controllers/BaseController.php
resources/assets/sass/main.scss
resources/views/columns_partials/topic.blade.php
resources/views/layouts_partials/top_bar.blade.php

https://mir24tv.atlassian.net/browse/MIP-104

Fix wrong fields

---

app/Http/Controllers/BaseController.php
app/Topic.php
resources/views/columns_partials/topic.blade.php

https://mir24tv.atlassian.net/browse/ST-557

fix published_at on front

---

app/Topic.php

https://mir24tv.atlassian.net/browse/ST-557

fix date accesor

---

resources/views/columns_partials/topic.blade.php
routes/web.php

https://mir24tv.atlassian.net/browse/MIP-109

download button for auth users only

---

app/Http/Controllers/Auth/LoginController.php

https://mir24tv.atlassian.net/browse/MIP-117

change redirect after login

---

resources/views/layouts_partials/top_bar.blade.php

https://mir24tv.atlassian.net/browse/MIP-118

Login from front

---

app/Console/Commands/TopicsDeleteOld.php
config/constants.php

https://mir24tv.atlassian.net/browse/MIP-28

fix old topics removal

---

resources/views/modals/partials/editableFields.blade.php

https://mir24tv.atlassian.net/browse/MIP-136

change status trigger inactive state name

---

public/css/core.css
resources/views/datatables/topic.blade.php

https://mir24tv.atlassian.net/browse/MIP-138

add search help to admin area

---

database/migrations/2018_06_18_125131_add_indexes.php

https://mir24tv.atlassian.net/browse/MIP-125

add indexes to bd

---

app/Http/Controllers/BaseController.php
resources/assets/js/search.js

https://mir24tv.atlassian.net/browse/MIP-66

Fix filter

---

resources/views/layouts/front.blade.php
webpack.mix.js

https://mir24tv.atlassian.net/browse/MIP-142

add assets versions

---

app/Http/Controllers/BaseController.php
resources/assets/js/search.js

https://mir24tv.atlassian.net/browse/MIP-66

Fix filter 2

---

config/constants.php
resources/views/columns_partials/topic.blade.php

https://mir24tv.atlassian.net/browse/MIP-143

Add new download link

---

app/User.php
composer.json
composer.lock
config/permission.php
database/migrations/2018_06_19_155626_create_permission_tables.php

https://mir24tv.atlassian.net/browse/MIP-144

add roles and create user and admin role

---

resources/views/layouts_partials/footer.blade.php

https://mir24tv.atlassian.net/browse/MIP-157

add contacts to front footer

---

resources/views/columns/organizations.blade.php

https://mir24tv.atlassian.net/browse/MIP-159

remove invite link from organizations

---

composer.json

https://mir24tv.atlassian.net/browse/MIP-161

fix date issue

---

resources/assets/sass/main.scss

https://mir24tv.atlassian.net/browse/MIP-163

move date to the right

---

resources/assets/sass/main.scss

https://mir24tv.atlassian.net/browse/MIP-166

Change date width to 150px, switch text-align to center.

---

app/Http/Controllers/TopicController.php
resources/assets/js/mainPage.js
resources/views/columns/topics.blade.php
resources/views/indexes/wow_index.blade.php
routes/web.php

https://mir24tv.atlassian.net/browse/MIP-178

Fix heart-memory load more
